// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fame_cpp
Rcpp::List fame_cpp(std::string plink_file, std::string pheno_file, std::string annotation_file, std::string covariate_file, int gxg_bin, int num_evec, int snp_index, int jack_number);
RcppExport SEXP _famer_fame_cpp(SEXP plink_fileSEXP, SEXP pheno_fileSEXP, SEXP annotation_fileSEXP, SEXP covariate_fileSEXP, SEXP gxg_binSEXP, SEXP num_evecSEXP, SEXP snp_indexSEXP, SEXP jack_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type plink_file(plink_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type pheno_file(pheno_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type annotation_file(annotation_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type covariate_file(covariate_fileSEXP);
    Rcpp::traits::input_parameter< int >::type gxg_bin(gxg_binSEXP);
    Rcpp::traits::input_parameter< int >::type num_evec(num_evecSEXP);
    Rcpp::traits::input_parameter< int >::type snp_index(snp_indexSEXP);
    Rcpp::traits::input_parameter< int >::type jack_number(jack_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(fame_cpp(plink_file, pheno_file, annotation_file, covariate_file, gxg_bin, num_evec, snp_index, jack_number));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_famer_fame_cpp", (DL_FUNC) &_famer_fame_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_famer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
