# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_openmp <- function() {
    .Call('_mmer_check_openmp', PACKAGE = 'mmer')
}

count_samples <- function(filename) {
    .Call('_mmer_count_samples', PACKAGE = 'mmer', filename)
}

count_fam <- function(filename) {
    .Call('_mmer_count_fam', PACKAGE = 'mmer', filename)
}

count_snps_bim <- function(filename) {
    .Call('_mmer_count_snps_bim', PACKAGE = 'mmer', filename)
}

mme_cpp <- function(plink_file, pheno_file, covariate_file, n_randvecs, n_blocks, rand_seed, gxg_indices, genotype_mask_file, n_threads) {
    .Call('_mmer_mme_cpp', PACKAGE = 'mmer', plink_file, pheno_file, covariate_file, n_randvecs, n_blocks, rand_seed, gxg_indices, genotype_mask_file, n_threads)
}

simulate_traits_cpp <- function(plink_file, additive_heritability, gxg_heritability, additive_snps, gxg_group_1, gxg_group_2) {
    .Call('_mmer_simulate_traits_cpp', PACKAGE = 'mmer', plink_file, additive_heritability, gxg_heritability, additive_snps, gxg_group_1, gxg_group_2)
}

