# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fame_cpp <- function(plink_file, pheno_file, covariate_file, n_randvecs, focal_snp_index, n_blocks, rand_seed) {
    .Call('_famer_fame_cpp', PACKAGE = 'famer', plink_file, pheno_file, covariate_file, n_randvecs, focal_snp_index, n_blocks, rand_seed)
}

