# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install OpenMP and HDF5
        if: runner.os != 'Windows'
        run: |
          if [[ "$(uname)" == "Darwin" ]]; then
            brew install hdf5
          elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libhdf5-serial-dev
            find /usr /opt -name "H5Ppublic.h"
          else
            choco install hdf5 --version=1.12.2
            mkdir -p ~/.R
            echo "CXXFLAGS=-I$(choco info hdf5 | grep 'Location' | cut -d':' -f2 | xargs)/include" >> ~/.R/Makevars
            echo "LDFLAGS=-L$(choco info hdf5 | grep 'Location' | cut -d':' -f2 | xargs)/lib" >> ~/.R/Makevars
          fi
          
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
