# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
      - name: Install dependencies on macOS and Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "$(uname)" = "Darwin" ]; then
            brew install hdf5
          elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libhdf5-serial-dev
            mkdir -p ~/.R
            touch ~/.R/Makevars
            echo "CPPFLAGS=-I/usr/include/hdf5/serial" >> ~/.R/Makevars
            echo "LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial" >> ~/.R/Makevars
          fi

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install hdf5 --version=1.12.2
          choco install szip --version=2.1.1

          # Fetch installation paths
          $HDF5_PATH = (choco info hdf5 | Select-String -Pattern "Location" | ForEach-Object { $_ -replace ".*: ", "" }).Trim()
          $SZIP_PATH = (choco info szip | Select-String -Pattern "Location" | ForEach-Object { $_ -replace ".*: ", "" }).Trim()

          # Configure R Makevars
          New-Item -ItemType Directory -Path $env:USERPROFILE\.R -Force
          Set-Content -Path $env:USERPROFILE\.R\Makevars -Value "CXXFLAGS=-I$HDF5_PATH\include -I$SZIP_PATH\include"
          Add-Content -Path $env:USERPROFILE\.R\Makevars -Value "LDFLAGS=-L$HDF5_PATH\lib -L$SZIP_PATH\lib -lsz"
          
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
